### ISSUE TITLE
Ubuntu Support?

### ISSUE THREAD

**Issue by offensivelyaverage** [bill-mavromatis/gnome-layout-manager#1]
The script doesn't seem to work on Ubuntu 16.04 LTS (GNOME 3.18) and Ubuntu 17.04 (3.24).

Two of the three layouts fail to apply, with the script stalling shortly after running and complaining that '[' or ']' is not enabled or installed.

![screen shot 2017-04-20 at 18 29 24](https://cloud.githubusercontent.com/assets/869982/25244106/516eac4c-25f7-11e7-8049-f69545eda825.png)

**Comment by vmavromatis** [comment]
Win and Mac layouts are still work-in-process but the extensions should still work. Please give it at least a full minute to work and ignore any errors the console spits out for now (they are used for debugging). 

After the script hit Alt-F2 and type 'r' to restart X session. Please let me know if this helped.

Added a notice on the readme that the script is still under development.

**Comment by vmavromatis** [comment]
I just tested the updated script on an Ubuntu GNOME 17.04 live CD and it worked fine.

**Comment by vmavromatis** [comment]
Closing since it seems to be working fine on Ubuntu. If any issues occur, I will reopen.
