### ISSUE TITLE
Infinite looping error

### ISSUE THREAD

**Issue by FastThenLeft** [bill-mavromatis/gnome-layout-manager#11]
Great program, thanks!

I used a fresh install of Ubuntu Gnome 17.04.  The first thing I do is run your script and pick Unity.  I get an infinite looping error (I waited 10 minutes!):

(gnome-shell:2609): St-WARNING **: Failed to load file:///home/david/.themes/United/gnome-shell/assets/ubuntu_launcher.svg: Error opening file /home/david/.themes/United/gnome-shell/assets/ubuntu_launcher.svg: No such file or directory

**Comment by vmavromatis** [comment]
Thank you! Sorry for the bug. I actually experienced the same this morning, it might have something to do with the United theme (maybe something like [this](https://github.com/godlyranchdressing/United-GNOME/issues/29)). I will check with the developer. If you hit Alt+F2 and type r and Enter, does it work?

**Comment by FastThenLeft** [comment]
No problem!  Thanks for the script.  Most everything is working.  I think I'm only missing the icon in the upper left on the sidebar and I can live without that for now.

When I followed your directions I got:
(gnome-shell:3092): St-WARNING **: Failed to load file:///home/david/.themes/United/gnome-shell/assets/ubuntu_launcher.svg: Error opening file /home/david/.themes/United/gnome-shell/assets/ubuntu_launcher.svg: No such file or directory
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/dash.js 760]: reference to undefined property oldApps[oldIndex]
Gjs-Message: JS WARNING: [resource:///org/gnome/shell/ui/appDisplay.js 1298]: reference to undefined property this.name

(gnome-shell:3092): St-WARNING **: Failed to load file:///home/david/.themes/United/gnome-shell/assets/ubuntu_launcher.svg: Error opening file /home/david/.themes/United/gnome-shell/assets/ubuntu_launcher.svg: No such file or directory

and then it went back into an infinite loop with the last error above.

**Comment by vmavromatis** [comment]
As a workaround, you could manually copy the file from https://github.com/godlyranchdressing/United-GNOME/blob/master/src/gnome-shell/assets/ubuntu_launcher.svg into /home/david/.themes/United/gnome-shell/assets/ until the theme developer issues a fix.

As such:
```cd $HOME/.themes/United/gnome-shell/assets/ && wget https://raw.githubusercontent.com/godlyranchdressing/United-GNOME/master/src/gnome-shell/assets/ubuntu_launcher.svg```

**Comment by FastThenLeft** [comment]
Works great!  Thanks!  Canonical should hire you to help them with the next version of Ubuntu Gnome!
