### ISSUE TITLE
Disable Zenity if option is specified

### ISSUE THREAD

**Issue by timsueberkrueb** [bill-mavromatis/gnome-layout-manager#12]
Right now, `layoutmanager` shows Zenity even if was launched with an option, e.g. `./layoutmanager.sh --unity`.
I think it would make sense to change this behavior by directly performing the actions without showing Zenity again when the script was launched with an option.

**Comment by vmavromatis** [comment]
It used to be like that, but after Zenity was added, arguments no longer work. I'll see what I can do! Flagging as enhancement.

**Comment by timsueberkrueb** [comment]
@bill-mavromatis cool! Thanks for your quick response and this project (it's fantastic :)).

**Comment by vmavromatis** [comment]
Got this working in /testing, merging soon!

**Comment by vmavromatis** [comment]
Merged 6e896195f698eec322df64c499532379591fda6b. Leaving open in case there are any bugs.

**Comment by timsueberkrueb** [comment]
@bill-mavromatis awesome, thank you, works fine here.
