### ISSUE TITLE
Restored configuration but top bar application menu is gone

### ISSUE THREAD

**Issue by RobinJ1995** [bill-mavromatis/gnome-layout-manager#18]
I tried some different layouts with gnome-layout-manager, but created a backup first. I decided that I liked my old layout better, so I restored it. However, the application menu in the top bar has disappeared.

![screenshot from 2017-05-23 11-30-02](https://cloud.githubusercontent.com/assets/3089559/26350524/6748f720-3fab-11e7-9f2e-3adff4537b6a.png)
(The one that's supposed to be here, from which you can access Nautilus' preferences among other things.)

I've looked through my Gnome Shell extensions and nothing seems to be enabled/disabled that wasn't in that state before. I've also tried running the commands in `/home/robin/.config/gnome-layout-manager/backup.txt` again (and restarted Gnome Shell) to see if that would fix it, but to no avail.

Any help in getting that menu back (and prevet the same thing from happening to others in future) would be appreciated ;-)

**Comment by vmavromatis** [comment]
Sorry for that! You should be able to get the menu back if you open "Tweak Tool" go to the "Top bar" settings and click "Show Applications Menu". I'll be making an update to the script very soon btw.

Also, it *might* be the case that you had an extension named "Applications Menu" activated but not sure.

**Comment by RobinJ1995** [comment]
Thanks, that was easier than expected :smile: Didn't realise this option was there (and assumed the script would've set it back to its initial value anyway).

I didn't have the "Applications Menu" extension enabled, by the way.

**Comment by vmavromatis** [comment]
@RobinJ1995 good to know it worked! I think I know the problem is that the script is not saving `gsettings get org.gnome.settings-daemon.plugins.xsettings overrides` which is where the option sits. I will keep the issue open until fixed!
