### ISSUE TITLE
Use appindicator support extension together with top icons

### ISSUE THREAD

**Issue by harry-cpp** [bill-mavromatis/gnome-layout-manager#2]
Due to how appindicator support and topicons extensions work you can run both of them side by side, the icons that are using libappindicator/KStatusNotifierItem will get turned into native indicators by the appindicator support extension while the rest will get loaded by topicons extension.

Extension in question: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by vmavromatis** [comment]
Nice idea! Added to TODO.

**Comment by vmavromatis** [comment]
Added with de8395f6a216fb3b9cbb603c4974c99976dd548a. Let me know if you have any issues.
