### ISSUE TITLE
ShellCheck linting

### ISSUE THREAD

**Issue by fuzzmz** [bill-mavromatis/gnome-layout-manager#4]
Ran the script through the shellcheck linter (online version here) and there are a couple of issues regarding undefined behavior and some globbing and word splitting issues.

I'd like to fix these if desired and maybe even set up CI to have shellcheck automatically run on pull requests.

![shellcheck-output](https://cloud.githubusercontent.com/assets/1335181/25477131/1e679f22-2b45-11e7-98b6-ce5b96dca83b.PNG)

**Comment by vmavromatis** [comment]
Thanks for that, many of those are leftovers from the old code, especially the unused parts. I will look into them, feel free to try any pull requests.

Flagging this as enchancement. I am looking at Github's CIs https://github.com/integrations/feature/continuous-integration
and cannot find a spellcheck/linting tool. Let me know what you used @fuzzmz and I can run after the last commit.

**Comment by JackHack96** [comment]
I've fixed many of these errors in #5
These are those remaining:
![https://i.imgur.com/C1FFAhl.png](https://i.imgur.com/C1FFAhl.png)

**Comment by vmavromatis** [comment]
Thanks to @JackHack96  now merged to master. I'm keeping this open until we can figure out an automated tool for SpellCheck.

Codacy looks good:
![codacy](https://cloud.githubusercontent.com/assets/8668731/25498845/648c6a96-2b81-11e7-9836-c12f8405b527.png)

**Comment by fuzzmz** [comment]
@bill-mavromatis , the first thing that popped into my mind on how to do CI was via [Travis CI](https://travis-ci.org/). In the build definition scheme we'd just have it install shellcheck and then run it over our script.

From there we can maybe start doing even more testing in the future, though since the function of this script is to edit the GUI that might be a bit harder via Travis.

**Comment by vmavromatis** [comment]
@fuzzmz Thanks. I looked into Travis CI but I think I prefer the simplicity of Codacy for now (it's just 1 bash script after all). I like how spellchecking is already built-in. I'm closing this then, thanks for your tips.
