### ISSUE TITLE
Idea for backup and restore

### ISSUE THREAD

**Issue by modoj** [bill-mavromatis/gnome-layout-manager#6]
Current settings can be easily pulled with 'dconf dump', or  'gsettings get', how about a script option for backup and restore? The necessary entries could be dumped to a backup file, and loaded with 'dconf load' easily, or 'gsettings set' with a little more work.

The simplest solution for backup and restore would be quick and dirty

'dconf dump /org/gnome/desktop/ > backup-file.txt'
and 
'dconf load /org/gnome/desktop/ < backup-file.txt'

Which should get the job done, but touches way more than necessary... this is fine FOR ME, but for release, when people will be running the script willy nilly after being posted on OMGUbuntu and the like, should be a more elegant approach. 

That would probably involve piping individual entries with 'gsettings get', and then parsing the backup to pull individual entries. 

I'm sure you're thinking, 'duh, you're not telling me anything I don't already know', I just wanted to get your thoughts on backup and restore, whether it's necessary, and if you have any thoughts on better implementing this, before I run off and do so myself.

**Comment by vmavromatis** [comment]
Hey I got many requests regarding that. It's a great idea. I will try to work with dconf dump/load and see how well it works. Feel free to make any pull requests. 

Flagging as enhancement.

**Comment by robyle** [comment]
when my system reboot . the layout will change to system default before. how can I save it by default login my system?

**Comment by vmavromatis** [comment]
@cyroby the standard behavior should be to save your layout. GNOME does not reset any extensions on reboot AFAIK. Could you give me any more details on which extensions/theme changes? Your settings are saved under your user, so if you're attempting to login as another user that might be causing it. Did you run the script as root by any chance? In that case try to re-run it as user.

**Comment by vmavromatis** [comment]
@modoj I have a very basic version of save/load function in the testing branch. If you want to test it, have a look here: https://github.com/bill-mavromatis/gnome-layout-manager/blob/testing/layoutmanager.sh

**Comment by vmavromatis** [comment]
Merged into master. Please open a new issue if you have any problems/ideas.
