### ISSUE TITLE
macOS layout

### ISSUE THREAD

**Issue by gnomelibre** [bill-mavromatis/gnome-layout-manager#7]
You could use the following projects:

Theme Gnome-OSX
https://www.gnome-look.org/p/1171688/

Icons La Capitaine
https://github.com/keeferrourke/la-capitaine-icon-theme

Font Garuda (it seems to be the closest to San Francisco)
Garuda Bold for window titles and Garuda Regular for the interface

Titlebar buttons on the left
gsettings set  org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'

**Comment by vmavromatis** [comment]
Titlebar buttons are already left on mac. Apart from that, awesome ideas thanks, this should be coming soon.

**Comment by vmavromatis** [comment]
Themes and icons should be working in testing branch. I'm looking into the font now and maybe a few extensions like activities configurator.

**Comment by vmavromatis** [comment]
Merged. Will be adding font too at a later time, Garuda was OK, but I would like to see some alternatives.
