### ISSUE TITLE
XDG directories

### ISSUE THREAD

**Issue by gnomelibre** [bill-mavromatis/gnome-layout-manager#8]
The script tries to save a wallpaper in the ~/Pictures folder, but this folder is localized in every languages. For exemple, in French it's not Pictures but Images. The list of the user's XDG folders is indicated in the file ~/.config/user-dirs.dirs

https://www.freedesktop.org/wiki/Software/xdg-user-dirs/

You can also use the xdg-user-dir command:

$ xdg-user-dir PICTURES
/home/gnomelibre/Images

**Comment by vmavromatis** [comment]
Good find, hotfixing with 3ae513306a4461d1c09dd8f91bc5c1bf961d4da6, let me know if that worked please.

**Comment by gnomelibre** [comment]
It's good for me ;-)
